/**
 * Copyright © 2021 by MooreSilicon.All rights reserved
 * @file  ms_dmac_regs.h
 * @brief
 * @author bingrui.chen
 * @date 2021-12-27
 * @version 1.0
 * @Revision
 */
#ifndef BLE_SOC_XXX_MS_DMAC_REGS_H_
#define BLE_SOC_XXX_MS_DMAC_REGS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup MS_REGISTER
 * @{
 */

/** @defgroup DmacChannel_Type DMAC Channel Registers definition
 * @{
 */
typedef struct
{
    volatile uint32_t SAR_L;
    volatile uint32_t SAR_H;
    volatile uint32_t DAR_L;
    volatile uint32_t DAR_H;
    volatile uint32_t LLP_L;
    volatile uint32_t LLP_H;
    volatile uint32_t CTL_L;
    volatile uint32_t CTL_H;
    volatile uint32_t SSTAT_L;
    volatile uint32_t SSTAT_H;
    volatile uint32_t DSTAT_L;
    volatile uint32_t DSTAT_H;
    volatile uint32_t SSTATAR_L;
    volatile uint32_t SSTATAR_H;
    volatile uint32_t DSTATAR_L;
    volatile uint32_t DSTATAR_H;
    volatile uint32_t CFG_L;
    volatile uint32_t CFG_H;
    volatile uint32_t SGR_L;
    volatile uint32_t SGR_H;
    volatile uint32_t DSR_L;
    volatile uint32_t DSR_H;
} DmacChannel_Type;

/**
 * @}
 */

/** @defgroup Dmac_Type DMA Controller Registers definition
 * @{
 */
typedef struct
{
    // Interrupt Registers
    volatile uint32_t RAWTFR_L;
    volatile uint32_t RAWTFR_H;
    volatile uint32_t RAWBLOCK_L;
    volatile uint32_t RAWBLOCK_H;
    volatile uint32_t RAWSRCTRAN_L;
    volatile uint32_t RAWSRCTRAN_H;
    volatile uint32_t RAWDSTTRAN_L;
    volatile uint32_t RAWDSTTRAN_H;
    volatile uint32_t RAWERR_L;
    volatile uint32_t RAWERR_H;
    volatile uint32_t STATUSTFR_L;
    volatile uint32_t STATUSTFR_H;
    volatile uint32_t STATUSBLOCK_L;
    volatile uint32_t STATUSBLOCK_H;
    volatile uint32_t STATUSSRCTRAN_L;
    volatile uint32_t STATUSSRCTRAN_H;
    volatile uint32_t STATUSDSTTRAN_L;
    volatile uint32_t STATUSDSTTRAN_H;
    volatile uint32_t STATUSERR_L;
    volatile uint32_t STATUSERR_H;
    volatile uint32_t MASKTFR_L;
    volatile uint32_t MASKTFR_H;
    volatile uint32_t MASKBLOCK_L;
    volatile uint32_t MASKBLOCK_H;
    volatile uint32_t MASKSRCTRAN_L;
    volatile uint32_t MASKSRCTRAN_H;
    volatile uint32_t MASKDSTTRAN_L;
    volatile uint32_t MASKDSTTRAN_H;
    volatile uint32_t MASKERR_L;
    volatile uint32_t MASKERR_H;
    volatile uint32_t CLEARTFR_L;
    volatile uint32_t CLEARTFR_H;
    volatile uint32_t CLEARBLOCK_L;
    volatile uint32_t CLEARBLOCK_H;
    volatile uint32_t CLEARSRCTRAN_L;
    volatile uint32_t CLEARSRCTRAN_H;
    volatile uint32_t CLEARDSTTRAN_L;
    volatile uint32_t CLEARDSTTRAN_H;
    volatile uint32_t CLEARERR_L;
    volatile uint32_t CLEARERR_H;
    volatile uint32_t STATUSINT_L;
    volatile uint32_t STATUSINT_H;
    // Software_Handshake Registers
    volatile uint32_t REQSRCREG_L;
    volatile uint32_t REQSRCREG_H;
    volatile uint32_t REQDSTREG_L;
    volatile uint32_t REQDSTREG_H;
    volatile uint32_t SGLRQQSRCREG_L;
    volatile uint32_t SGLRQQSRCREG_H;
    volatile uint32_t SGLRQQDSTREG_L;
    volatile uint32_t SGLRQQDSTREG_H;
    volatile uint32_t LSTSRCREG_L;
    volatile uint32_t LSTSRCREG_H;
    volatile uint32_t LSTDSTREG_L;
    volatile uint32_t LSTDSTREG_H;
    // Miscellaneous Registers
    volatile uint32_t CFGREG_L;
    volatile uint32_t CFGREG_H;
    volatile uint32_t CHENREG_L;
    volatile uint32_t CHENREG_H;
    volatile uint32_t IDREG_L;
    volatile uint32_t IDREG_H;
    volatile uint32_t TESTREG_L;
    volatile uint32_t TESTREG_H;
    volatile uint32_t LPTIMEOUTREG_L;
    volatile uint32_t LPTIMEOUTREG_H;
    volatile uint32_t COMP_PARAMS_6_L;
    volatile uint32_t COMP_PARAMS_6_H;
    volatile uint32_t COMP_PARAMS_5_L;
    volatile uint32_t COMP_PARAMS_5_H;
    volatile uint32_t COMP_PARAMS_4_L;
    volatile uint32_t COMP_PARAMS_4_H;
    volatile uint32_t COMP_PARAMS_3_L;
    volatile uint32_t COMP_PARAMS_3_H;
    volatile uint32_t COMP_PARAMS_2_L;
    volatile uint32_t COMP_PARAMS_2_H;
    volatile uint32_t COMP_PARAMS_1_L;
    volatile uint32_t COMP_PARAMS_1_H;
    volatile uint32_t COMPSID_L;
    volatile uint32_t COMPSID_H;
} Dmac_Type;
/**
 * @}
 */

/*Low Word Control Register for Channel x*/
#define DMAC_CHNNL_CTL_L_INT_EN_POS							(0UL)
#define DMAC_CHNNL_CTL_L_INT_EN_MASK						((1UL) << DMAC_CHNNL_CTL_L_INT_EN_POS)
#define DMAC_CHNNL_CTL_L_INT_EN								DMAC_CHNNL_CTL_L_INT_EN_MASK
#define DMAC_CHNNL_CTL_L_DST_TR_WIDTH_POS					(1UL)
#define DMAC_CHNNL_CTL_L_DST_TR_WIDTH_MASK					((0x7UL) << DMAC_CHNNL_CTL_L_DST_TR_WIDTH_POS)
#define DMAC_CHNNL_CTL_L_DST_TR_WIDTH						DMAC_CHNNL_CTL_L_DST_TR_WIDTH_MASK
#define DMAC_CHNNL_CTL_L_SRC_TR_WIDTH_POS					(4UL)
#define DMAC_CHNNL_CTL_L_SRC_TR_WIDTH_MASK					((0X7UL) << DMAC_CHNNL_CTL_L_SRC_TR_WIDTH_POS)
#define DMAC_CHNNL_CTL_L_SRC_TR_WIDTH						DMAC_CHNNL_CTL_L_SRC_TR_WIDTH_MASK
#define DMAC_CHNNL_CTL_L_DINC_POS							(7UL)
#define DMAC_CHNNL_CTL_L_DINC_MASK							((0X3UL) << DMAC_CHNNL_CTL_L_DINC_POS)
#define DMAC_CHNNL_CTL_L_DINC								DMAC_CHNNL_CTL_L_DINC_MASK
#define DMAC_CHNNL_CTL_L_SINC_POS							(9UL)
#define DMAC_CHNNL_CTL_L_SINC_MASK							((0X3UL) << DMAC_CHNNL_CTL_L_SINC_POS)
#define DMAC_CHNNL_CTL_L_SINC								DMAC_CHNNL_CTL_L_SINC_MASK
#define DMAC_CHNNL_CTL_L_DST_MSIZE_POS						(11UL)
#define DMAC_CHNNL_CTL_L_DST_MSIZE_MASK						((0X7UL) << DMAC_CHNNL_CTL_L_DST_MSIZE_POS)
#define DMAC_CHNNL_CTL_L_DST_MSIZE							DMAC_CHNNL_CTL_L_DST_MSIZE_MASK
#define DMAC_CHNNL_CTL_L_SRC_MSIZE_POS						(14UL)
#define DMAC_CHNNL_CTL_L_SRC_MSIZE_MASK						((0X7UL) << DMAC_CHNNL_CTL_L_SRC_MSIZE_POS)
#define DMAC_CHNNL_CTL_L_SRC_MSIZE							DMAC_CHNNL_CTL_L_SRC_MSIZE_MASK
#define DMAC_CHNNL_CTL_L_SRC_GATHER_EN_POS					(17UL)
#define DMAC_CHNNL_CTL_L_SRC_GATHER_EN_MASK					((0X1UL) << DMAC_CHNNL_CTL_L_SRC_GATHER_EN_POS)
#define DMAC_CHNNL_CTL_L_SRC_GATHER_EN						DMAC_CHNNL_CTL_L_SRC_GATHER_EN_MASK
#define DMAC_CHNNL_CTL_L_DST_SCATTER_EN_POS					(18UL)
#define DMAC_CHNNL_CTL_L_DST_SCATTER_EN_MASK				((0X1UL) << DMAC_CHNNL_CTL_L_DST_SCATTER_EN_POS)
#define DMAC_CHNNL_CTL_L_DST_SCATTER_EN						DMAC_CHNNL_CTL_L_DST_SCATTER_EN_MASK
#define DMAC_CHNNL_CTL_L_TT_FC_POS							(20UL)
#define DMAC_CHNNL_CTL_L_TT_FC_MASK							((0X7UL) << DMAC_CHNNL_CTL_L_TT_FC_POS)
#define DMAC_CHNNL_CTL_L_TT_FC								DMAC_CHNNL_CTL_L_TT_FC_MASK
#define DMAC_CHNNL_CTL_L_DMS_POS							(23UL)
#define DMAC_CHNNL_CTL_L_DMS_MASK							((0X3UL) << DMAC_CHNNL_CTL_L_DMS_POS)
#define DMAC_CHNNL_CTL_L_DMS								DMAC_CHNNL_CTL_L_DMS_MASK
#define DMAC_CHNNL_CTL_L_SMS_POS							(26UL)
#define DMAC_CHNNL_CTL_L_SMS_MASK							((0X3UL) << DMAC_CHNNL_CTL_L_SMS_POS)
#define DMAC_CHNNL_CTL_L_SMS								DMAC_CHNNL_CTL_L_SMS_MASK
#define DMAC_CHNNL_CTL_L_LLR_DST_EN_POS						(28UL)
#define DMAC_CHNNL_CTL_L_LLR_DST_EN_MASK					((0X1UL) << DMAC_CHNNL_CTL_L_LLR_DST_EN_POS)
#define DMAC_CHNNL_CTL_L_LLR_DST_EN							DMAC_CHNNL_CTL_L_LLR_DST_EN_MASK
#define DMAC_CHNNL_CTL_L_LLR_SRC_EN_POS						(29UL)
#define DMAC_CHNNL_CTL_L_LLR_SRC_EN_MASK					((0X1UL) << DMAC_CHNNL_CTL_L_LLR_SRC_EN_POS)
#define DMAC_CHNNL_CTL_L_LLR_SRC_EN							DMAC_CHNNL_CTL_L_LLR_SRC_EN_MASK

/*High Word Control Register for Channel x*/
#define DMAC_CHNNL_CTL_H_BLOCK_TS_POS						(0UL)
#define DMAC_CHNNL_CTL_H_BLOCK_TS_MASK						((0XFFFUL) << DMAC_CHNNL_CTL_H_BLOCK_TS_POS)
#define DMAC_CHNNL_CTL_H_BLOCK_TS							DMAC_CHNNL_CTL_H_BLOCK_TS_MASK
#define DMAC_CHNNL_CTL_H_DONE_POS							(12UL)
#define DMAC_CHNNL_CTL_H_DONE_MASK							((0X1UL) << DMAC_CHNNL_CTL_H_DONE_POS)
#define DMAC_CHNNL_CTL_H_DONE								DMAC_CHNNL_CTL_H_DONE_MASK

/*Low Word Configuration Register for Channel x*/
#define DMAC_CHNNL_CFG_L_CH_PRIOR_POS						(5UL)
#define DMAC_CHNNL_CFG_L_CH_PRIOR_MASK						((0X7UL) << DMAC_CHNNL_CFG_L_CH_PRIOR_POS)
#define DMAC_CHNNL_CFG_L_CH_PRIOR							DMAC_CHNNL_CFG_L_CH_PRIOR_MASK
#define DMAC_CHNNL_CFG_L_CH_SUSP_POS						(8UL)
#define DMAC_CHNNL_CFG_L_CH_SUSP_MASK						((0X1UL) << DMAC_CHNNL_CFG_L_CH_SUSP_POS)
#define DMAC_CHNNL_CFG_L_CH_SUSP							DMAC_CHNNL_CFG_L_CH_SUSP_MASK
#define DMAC_CHNNL_CFG_L_FIFO_EMPTY_POS						(9UL)
#define DMAC_CHNNL_CFG_L_FIFO_EMPTY_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_FIFO_EMPTY_POS)
#define DMAC_CHNNL_CFG_L_FIFO_EMPTY							DMAC_CHNNL_CFG_L_FIFO_EMPTY_MASK
#define DMAC_CHNNL_CFG_L_HS_SEL_DST_POS						(10UL)
#define DMAC_CHNNL_CFG_L_HS_SEL_DST_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_HS_SEL_DST_POS)
#define DMAC_CHNNL_CFG_L_HS_SEL_DST							DMAC_CHNNL_CFG_L_HS_SEL_DST_MASK
#define DMAC_CHNNL_CFG_L_HS_SEL_SRC_POS						(11UL)
#define DMAC_CHNNL_CFG_L_HS_SEL_SRC_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_HS_SEL_SRC_POS)
#define DMAC_CHNNL_CFG_L_HS_SEL_SRC							DMAC_CHNNL_CFG_L_HS_SEL_SRC_MASK
#define DMAC_CHNNL_CFG_L_LOCK_CH_L_POS						(12UL)
#define DMAC_CHNNL_CFG_L_LOCK_CH_L_MASK						((0X3UL) << DMAC_CHNNL_CFG_L_LOCK_CH_L_POS)
#define DMAC_CHNNL_CFG_L_LOCK_CH_L							DMAC_CHNNL_CFG_L_LOCK_CH_L_MASK
#define DMAC_CHNNL_CFG_L_LOCK_B_L_POS						(14UL)
#define DMAC_CHNNL_CFG_L_LOCK_B_L_MASK						((0X3UL) << DMAC_CHNNL_CFG_L_LOCK_B_L_POS)
#define DMAC_CHNNL_CFG_L_LOCK_B_L							DMAC_CHNNL_CFG_L_LOCK_B_L_MASK
#define DMAC_CHNNL_CFG_L_LOCK_CH_POS						(16UL)
#define DMAC_CHNNL_CFG_L_LOCK_CH_MASK						((0X1UL) << DMAC_CHNNL_CFG_L_LOCK_CH_POS)
#define DMAC_CHNNL_CFG_L_LOCK_CH							DMAC_CHNNL_CFG_L_LOCK_CH_MASK
#define DMAC_CHNNL_CFG_L_LOCK_B_POS							(17UL)
#define DMAC_CHNNL_CFG_L_LOCK_B_MASK						((0X1UL) << DMAC_CHNNL_CFG_L_LOCK_B_POS)
#define DMAC_CHNNL_CFG_L_LOCK_B								DMAC_CHNNL_CFG_L_LOCK_B_MASK
#define DMAC_CHNNL_CFG_L_DST_HS_POL_POS						(18UL)
#define DMAC_CHNNL_CFG_L_DST_HS_POL_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_DST_HS_POL_POS)
#define DMAC_CHNNL_CFG_L_DST_HS_POL							DMAC_CHNNL_CFG_L_DST_HS_POL_MASK
#define DMAC_CHNNL_CFG_L_SRC_HS_POL_POS						(19UL)
#define DMAC_CHNNL_CFG_L_SRC_HS_POL_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_SRC_HS_POL_POS)
#define DMAC_CHNNL_CFG_L_SRC_HS_POL							DMAC_CHNNL_CFG_L_SRC_HS_POL_MASK
#define DMAC_CHNNL_CFG_L_MAX_ABRST_POS						(20UL)
#define DMAC_CHNNL_CFG_L_MAX_ABRST_MASK						((0X3FFUL) << DMAC_CHNNL_CFG_L_MAX_ABRST_POS)
#define DMAC_CHNNL_CFG_L_MAX_ABRST							DMAC_CHNNL_CFG_L_MAX_ABRST_MASK
#define DMAC_CHNNL_CFG_L_RELOAD_SRC_POS						(30UL)
#define DMAC_CHNNL_CFG_L_RELOAD_SRC_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_RELOAD_SRC_POS)
#define DMAC_CHNNL_CFG_L_RELOAD_SRC							DMAC_CHNNL_CFG_L_RELOAD_SRC_MASK
#define DMAC_CHNNL_CFG_L_RELOAD_DST_POS						(31UL)
#define DMAC_CHNNL_CFG_L_RELOAD_DST_MASK					((0X1UL) << DMAC_CHNNL_CFG_L_RELOAD_DST_POS)
#define DMAC_CHNNL_CFG_L_RELOAD_DST							DMAC_CHNNL_CFG_L_RELOAD_DST_MASK

/*High Word Configuration Register for Channel x*/
#define DMAC_CHNNL_CFG_H_FCMODE_POS							(0UL)
#define DMAC_CHNNL_CFG_H_FCMODE_MASK						((0X1UL) << DMAC_CHNNL_CFG_H_FCMODE_POS)
#define DMAC_CHNNL_CFG_H_FCMODE								DMAC_CHNNL_CFG_H_FCMODE_MASK
#define DMAC_CHNNL_CFG_H_FIFO_MODE_POS						(1UL)
#define DMAC_CHNNL_CFG_H_FIFO_MODE_MASK						((0X1UL) << DMAC_CHNNL_CFG_H_FIFO_MODE_POS)
#define DMAC_CHNNL_CFG_H_FIFO_MODE							DMAC_CHNNL_CFG_H_FIFO_MODE_MASK
#define DMAC_CHNNL_CFG_H_PROTCTL_POS						(2UL)
#define DMAC_CHNNL_CFG_H_PROTCTL_MASK						((0X7UL) << DMAC_CHNNL_CFG_H_PROTCTL_POS)
#define DMAC_CHNNL_CFG_H_PROTCTL							DMAC_CHNNL_CFG_H_PROTCTL_MASK
#define DMAC_CHNNL_CFG_H_DS_UPD_EN_POS						(5UL)
#define DMAC_CHNNL_CFG_H_DS_UPD_EN_MASK						((0X1UL) << DMAC_CHNNL_CFG_H_DS_UPD_EN_POS)
#define DMAC_CHNNL_CFG_H_DS_UPD_EN							DMAC_CHNNL_CFG_H_DS_UPD_EN_MASK
#define DMAC_CHNNL_CFG_H_SS_UPD_EN_POS						(6UL)
#define DMAC_CHNNL_CFG_H_SS_UPD_EN_MASK						((0X1UL) << DMAC_CHNNL_CFG_H_SS_UPD_EN_POS)
#define DMAC_CHNNL_CFG_H_SS_UPD_EN							DMAC_CHNNL_CFG_H_SS_UPD_EN_MASK
#define DMAC_CHNNL_CFG_H_SRC_PRE_POS						(7UL)
#define DMAC_CHNNL_CFG_H_SRC_PRE_MASK						((0XFUL) << DMAC_CHNNL_CFG_H_SRC_PRE_POS)
#define DMAC_CHNNL_CFG_H_SRC_PRE						    DMAC_CHNNL_CFG_H_SRC_PRE_MASK
#define DMAC_CHNNL_CFG_H_DST_PRE_POS					    (11UL)
#define DMAC_CHNNL_CFG_H_DST_PRE_MASK					    ((0XFUL) << DMAC_CHNNL_CFG_H_DST_PRE_POS)
#define DMAC_CHNNL_CFG_H_DST_PRE						    DMAC_CHNNL_CFG_H_DST_PRE_MASK

/*Source Gather Register for Channel x*/
#define DMAC_CHNNL_SGR_L_SGC_POS						(1UL)
#define DMAC_CHNNL_SGR_L_SGC_MASK						((0X7FFUL) << DMAC_CHNNL_SGR_L_SGC_POS)
#define DMAC_CHNNL_SGR_L_SGC							DMAC_CHNNL_SGR_L_SGC_MASK
#define DMAC_CHNNL_SGR_L_SGI_POS						(12UL)
#define DMAC_CHNNL_SGR_L_SGI_MASK						((0XFFFFFUL) << DMAC_CHNNL_SGR_L_SGI_POS)
#define DMAC_CHNNL_SGR_L_SGI							DMAC_CHNNL_SGR_L_SGI_MASK

/*Destination Scatter Register for Channel x*/
#define DMAC_CHNNL_DGR_L_SGC_POS						(1UL)
#define DMAC_CHNNL_DGR_L_SGC_MASK						((0X7FFUL) << DMAC_CHNNL_DGR_L_SGC_POS)
#define DMAC_CHNNL_DGR_L_SGC							DMAC_CHNNL_DGR_L_SGC_MASK
#define DMAC_CHNNL_DGR_L_SGI_POS						(12UL)
#define DMAC_CHNNL_DGR_L_SGI_MASK						((0XFFFFFUL) << DMAC_CHNNL_DGR_L_SGI_POS)
#define DMAC_CHNNL_DGR_L_SGI							DMAC_CHNNL_DGR_L_SGI_MASK

/*DMAC Raw Status for IntTfr Interrupt*/
#define DMAC_RAWTFR_L_RAW_POS							(0UL)
#define DMAC_RAWTFR_L_RAW_MASK							((0X3FUL) << DMAC_RAWTFR_L_RAW_POS)
#define DMAC_RAWTFR_L_RAW								DMAC_RAWTFR_L_RAW_MASK

/*DMAC Raw Status for IntBlock Interrupt*/
#define DMAC_RAWBLOCK_L_RAW_POS							(0UL)
#define DMAC_RAWBLOCK_L_RAW_MASK						((0X3FUL) << DMAC_RAWBLOCK_L_RAW_POS)
#define DMAC_RAWBLOCK_L_RAW								DMAC_RAWBLOCK_L_RAW_MASK

/*DMAC Raw Status for IntSrcTran Interrupt*/
#define DMAC_RAWSRCTRAN_L_RAW_POS						(0UL)
#define DMAC_RAWSRCTRAN_L_RAW_MASK						((0X3FUL) << DMAC_RAWSRCTRAN_L_RAW_POS)
#define DMAC_RAWSRCTRAN_L_RAW							DMAC_RAWSRCTRAN_L_RAW_MASK

/*DMAC Raw Status for IntDstTran Interrupt*/
#define DMAC_RAWDSTTRAN_L_RAW_POS						(0UL)
#define DMAC_RAWDSTTRAN_L_RAW_MASK						((0X3FUL) << DMAC_RAWDSTTRAN_L_RAW_POS)
#define DMAC_RAWDSTTRAN_L_RAW							DMAC_RAWDSTTRAN_L_RAW_MASK

/*DMAC Raw Status for IntErr Interrupt*/
#define DMAC_RAWERR_L_RAW_POS							(0UL)
#define DMAC_RAWERR_L_RAW_MASK							((0X3FUL) << DMAC_RAWERR_L_RAW_POS)
#define DMAC_RAWERR_L_RAW								DMAC_RAWERR_L_RAW_MASK

/*DMAC Status for IntTfr Interrupt*/
#define DMAC_STATUSTFR_L_STATUS_POS						(0UL)
#define DMAC_STATUSTFR_L_STATUS_MASK					((0X3FUL) << DMAC_STATUSTFR_L_STATUS_POS)
#define DMAC_STATUSTFR_L_STATUS							DMAC_STATUSTFR_L_STATUS_MASK

/*DMAC Status for IntBlock Interrupt*/
#define DMAC_STATUSBLOCK_L_STATUS_POS					(0UL)
#define DMAC_STATUSBLOCK_L_STATUS_MASK					((0X3FUL) << DMAC_STATUSBLOCK_L_STATUS_POS)
#define DMAC_STATUSBLOCK_L_STATUS						DMAC_STATUSBLOCK_L_STATUS_MASK

/*DMAC Status for IntSrcTran Interrupt*/
#define DMAC_STATUSSRCTRAN_L_STATUS_POS					(0UL)
#define DMAC_STATUSSRCTRAN_L_STATUS_MASK				((0X3FUL) << DMAC_STATUSSRCTRAN_L_STATUS_POS)
#define DMAC_STATUSSRCTRAN_L_STATUS						DMAC_STATUSSRCTRAN_L_STATUS_MASK

/*DMAC Status for IntDstTran Interrupt*/
#define DMAC_STATUSDSTTRAN_L_STATUS_POS					(0UL)
#define DMAC_STATUSDSTTRAN_L_STATUS_MASK				((0X3FUL) << DMAC_STATUSDSTTRAN_L_STATUS_POS)
#define DMAC_STATUSDSTTRAN_L_STATUS						DMAC_STATUSDSTTRAN_L_STATUS_MASK

/*DMAC Status for IntErr Interrupt*/
#define DMAC_STATUSERR_L_STATUS_POS						(0UL)
#define DMAC_STATUSERR_L_STATUS_MASK					((0X3FUL) << DMAC_STATUSERR_L_STATUS_POS)
#define DMAC_STATUSERR_L_STATUS							DMAC_STATUSERR_L_STATUS_MASK

/*DMAC Mask  for IntTfr Interrupt*/
#define DMAC_MASKTFR_L_INT_MASK_POS						(0UL)
#define DMAC_MASKTFR_L_INT_MASK_MASK					((0X3FUL) << DMAC_MASKTFR_L_INT_MASK_POS)
#define DMAC_MASKTFR_L_INT_MASK							DMAC_MASKTFR_L_INT_MASK_MASK
#define DMAC_MASKTFR_L_INT_MASK_WE_POS					(8UL)
#define DMAC_MASKTFR_L_INT_MASK_WE_MASK					((0X3FUL) << DMAC_MASKTFR_L_INT_MASK_WE_POS)
#define DMAC_MASKTFR_L_INT_MASK_WE						DMAC_MASKTFR_L_INT_MASK_WE_MASK

/*DMAC Mask for IntBlock Interrupt*/
#define DMAC_MASKBLOCK_L_INT_MASK_POS					(0UL)
#define DMAC_MASKBLOCK_L_INT_MASK_MASK					((0X3FUL) << DMAC_MASKBLOCK_L_INT_MASK_POS)
#define DMAC_MASKBLOCK_L_INT_MASK						DMAC_MASKBLOCK_L_INT_MASK_MASK
#define DMAC_MASKBLOCK_L_INT_MASK_WE_POS				(8UL)
#define DMAC_MASKBLOCK_L_INT_MASK_WE_MASK				((0X3FUL) << DMAC_MASKBLOCK_L_INT_MASK_WE_POS)
#define DMAC_MASKBLOCK_L_INT_MASK_WE					DMAC_MASKBLOCK_L_INT_MASK_WE_MASK

/*DMAC  Mask for IntSrcTran Interrupt*/
#define DMAC_MASKSRCTRAN_L_INT_MASK_POS					(0UL)
#define DMAC_MASKSRCTRAN_L_INT_MASK_MASK				((0X3FUL) << DMAC_MASKSRCTRAN_L_INT_MASK_POS)
#define DMAC_MASKSRCTRAN_L_INT_MASK						DMAC_MASKSRCTRAN_L_INT_MASK_MASK
#define DMAC_MASKSRCTRAN_L_INT_MASK_WE_POS				(8UL)
#define DMAC_MASKSRCTRAN_L_INT_MASK_WE_MASK				((0X3FUL) << DMAC_MASKSRCTRAN_L_INT_MASK_WE_POS)
#define DMAC_MASKSRCTRAN_L_INT_MASK_WE					DMAC_MASKSRCTRAN_L_INT_MASK_WE_MASK

/*DMAC  Mask for IntDstTran Interrupt*/
#define DMAC_MASKDSTTRAN_L_INT_MASK_POS					(0UL)
#define DMAC_MASKDSTTRAN_L_INT_MASK_MASK				((0X3FUL) << DMAC_MASKDSTTRAN_L_INT_MASK_POS)
#define DMAC_MASKDSTTRAN_L_INT_MASK						DMAC_MASKDSTTRAN_L_INT_MASK_MASK
#define DMAC_MASKDSTTRAN_L_INT_MASK_WE_POS				(8UL)
#define DMAC_MASKDSTTRAN_L_INT_MASK_WE_MASK				((0X3FUL) << DMAC_MASKDSTTRAN_L_INT_MASK_WE_POS)
#define DMAC_MASKDSTTRAN_L_INT_MASK_WE					DMAC_MASKDSTTRAN_L_INT_MASK_WE_MASK

/*DMAC  Mask for IntErr Interrupt*/
#define DMAC_MASKERR_L_INT_MASK_POS						(0UL)
#define DMAC_MASKERR_L_INT_MASK_MASK					((0X3FUL) << DMAC_MASKERR_L_INT_MASK_POS)
#define DMAC_MASKERR_L_INT_MASK							DMAC_MASKERR_L_INT_MASK_MASK
#define DMAC_MASKERR_L_INT_MASK_WE_POS					(8UL)
#define DMAC_MASKERR_L_INT_MASK_WE_MASK					((0X3FUL) << DMAC_MASKERR_L_INT_MASK_WE_POS)
#define DMAC_MASKERR_L_INT_MASK_WE						DMAC_MASKERR_L_INT_MASK_WE_MASK

/*DMAC   Clear for IntTfr Interrupt*/
#define DMAC_CLEARTFR_L_CLEAR_POS						(0UL)
#define DMAC_CLEARTFR_L_CLEAR_MASK						((0X3FUL) << DMAC_CLEARTFR_L_CLEAR_POS)
#define DMAC_CLEARTFR_L_CLEAR							DMAC_CLEARTFR_L_CLEAR_MASK

/*DMAC  Clear for IntBlock Interrupt*/
#define DMAC_CLEARBLOCK_L_CLEAR_POS						(0UL)
#define DMAC_CLEARBLOCK_L_CLEAR_MASK					((0X3FUL) << DMAC_CLEARBLOCK_L_CLEAR_POS)
#define DMAC_CLEARBLOCK_L_CLEAR							DMAC_CLEARBLOCK_L_CLEAR_MASK

/*DMAC  Clear for IntSrcTran Interrupt*/
#define DMAC_CLEARSRCTRAN_L_CLEAR_POS					(0UL)
#define DMAC_CLEARSRCTRAN_L_CLEAR_MASK					((0X3FUL) << DMAC_CLEARSRCTRAN_L_CLEAR_POS)
#define DMAC_CLEARSRCTRAN_L_CLEAR						DMAC_CLEARSRCTRAN_L_CLEAR_MASK

/*DMAC  Clear for IntDstTran Interrupt*/
#define DMAC_CLEARDSTTRAN_L_CLEAR_POS					(0UL)
#define DMAC_CLEARDSTTRAN_L_CLEAR_MASK					((0X3FUL) << DMAC_CLEARDSTTRAN_L_CLEAR_POS)
#define DMAC_CLEARDSTTRAN_L_CLEAR						DMAC_CLEARDSTTRAN_L_CLEAR_MASK

/*DMAC  Clear for IntErr Interrupt*/
#define DMAC_CLEARERR_L_CLEAR_POS						(0UL)
#define DMAC_CLEARERR_L_CLEAR_MASK						((0X3FUL) << DMAC_CLEARERR_L_CLEAR_POS)
#define DMAC_CLEARERR_L_CLEAR							DMAC_CLEARERR_L_CLEAR_MASK

/*DMAC  Status for each Interrupt type*/
#define DMAC_STATUSINT_L_TRF_POS						(0UL)
#define DMAC_STATUSINT_L_TRF_MASK						((0X1UL) << DMAC_STATUSINT_L_TRF_POS)
#define DMAC_STATUSINT_L_TRF							DMAC_STATUSINT_L_TRF_MASK
#define DMAC_STATUSINT_L_BLOCK_POS						(1UL)
#define DMAC_STATUSINT_L_BLOCK_MASK						((0X1UL) << DMAC_STATUSINT_L_BLOCK_POS)
#define DMAC_STATUSINT_L_BLOCK							DMAC_STATUSINT_L_BLOCK_MASK
#define DMAC_STATUSINT_L_SRCT_POS						(2UL)
#define DMAC_STATUSINT_L_SRCT_MASK						((0X1UL) << DMAC_STATUSINT_L_SRCT_POS)
#define DMAC_STATUSINT_L_SRCT							DMAC_STATUSINT_L_SRCT_MASK
#define DMAC_STATUSINT_L_DSTT_POS						(3UL)
#define DMAC_STATUSINT_L_DSTT_MASK						((0X1UL) << DMAC_STATUSINT_L_DSTT_POS)
#define DMAC_STATUSINT_L_DSTT							DMAC_STATUSINT_L_DSTT_MASK
#define DMAC_STATUSINT_L_ERR_POS						(4UL)
#define DMAC_STATUSINT_L_ERR_MASK						((0X1UL) << DMAC_STATUSINT_L_ERR_POS)
#define DMAC_STATUSINT_L_ERR							DMAC_STATUSINT_L_ERR_MASK

/*DMAC  Source Software Transaction Request register*/
#define DMAC_REQSRCREG_L_SRC_REQ_POS					(0UL)
#define DMAC_REQSRCREG_L_SRC_REQ_MASK					((0X3FUL) << DMAC_REQSRCREG_L_SRC_REQ_POS)
#define DMAC_REQSRCREG_L_SRC_REQ						DMAC_REQSRCREG_L_SRC_REQ_MASK
#define DMAC_REQSRCREG_L_SRC_REQ_WE_POS					(8UL)
#define DMAC_REQSRCREG_L_SRC_REQ_WE_MASK				((0X3FUL) << DMAC_REQSRCREG_L_SRC_REQ_WE_POS)
#define DMAC_REQSRCREG_L_SRC_REQ_WE						DMAC_REQSRCREG_L_SRC_REQ_WE_MASK

/*DMAC  Destination Software Transaction Request register*/
#define DMAC_REQDSTREG_L_DST_REQ_POS					(0UL)
#define DMAC_REQDSTREG_L_DST_REQ_MASK					((0X3FUL) << DMAC_REQDSTREG_L_DST_REQ_POS)
#define DMAC_REQDSTREG_L_DST_REQ						DMAC_REQDSTREG_L_DST_REQ_MASK
#define DMAC_REQDSTREG_L_DST_REQ_WE_POS					(8UL)
#define DMAC_REQDSTREG_L_DST_REQ_WE_MASK				((0X3FUL) << DMAC_REQDSTREG_L_DST_REQ_WE_POS)
#define DMAC_REQDSTREG_L_DST_REQ_WE						DMAC_REQDSTREG_L_DST_REQ_WE_MASK

/*DMAC Source Single Transaction Request register*/
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ_POS				(0UL)
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ_MASK				((0X3FUL) << DMAC_SGLRQSRCREG_L_SRC_SGLREQ_POS)
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ					DMAC_SGLRQSRCREG_L_SRC_SGLREQ_MASK
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ_WE_POS			(8UL)
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ_WE_MASK			((0X3FUL) << DMAC_SGLRQSRCREG_L_SRC_SGLREQ_WE_POS)
#define DMAC_SGLRQSRCREG_L_SRC_SGLREQ_WE				DMAC_SGLRQSRCREG_L_SRC_SGLREQ_WE_MASK

/*DMAC Destination Single Transaction Request register*/
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ_POS				(0UL)
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ_MASK				((0X3FUL) << DMAC_SGLRQDSTREG_L_DST_SGLREQ_POS)
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ					DMAC_SGLRQDSTREG_L_DST_SGLREQ_MASK
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ_WE_POS			(8UL)
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ_WE_MASK			((0X3FUL) << DMAC_SGLRQDSTREG_L_DST_SGLREQ_WE_POS)
#define DMAC_SGLRQDSTREG_L_DST_SGLREQ_WE				DMAC_SGLRQDSTREG_L_DST_SGLREQ_WE_MASK

/*DMAC Source Last Transaction Request register*/
#define DMAC_LSTSRCREG_L_LSTSRC_POS						(0UL)
#define DMAC_LSTSRCREG_L_LSTSRC_MASK					((0X3FUL) << DMAC_LSTSRCREG_L_LSTSRC_POS)
#define DMAC_LSTSRCREG_L_LSTSRC							DMAC_LSTSRCREG_L_LSTSRC_MASK
#define DMAC_LSTSRCREG_L_LSTSRC_WE_POS					(8UL)
#define DMAC_LSTSRCREG_L_LSTSRC_WE_MASK					((0X3FUL) << DMAC_LSTSRCREG_L_LSTSRC_WE_POS)
#define DMAC_LSTSRCREG_L_LSTSRC_WE						DMAC_LSTSRCREG_L_LSTSRC_WE_MASK

/*DMAC Destination Last Transaction Request register*/
#define DMAC_LSTDSTREG_LSTDST_POS						(0UL)
#define DMAC_LSTDSTREG_LSTDST_MASK						((0X3FUL) << DMAC_LSTDSTREG_LSTDST_POS)
#define DMAC_LSTDSTREG_LSTDST							DMAC_LSTDSTREG_LSTDST_MASK
#define DMAC_LSTDSTREG_LSTDST_WE_POS					(8UL)
#define DMAC_LSTDSTREG_LSTDST_WE_MASK					((0X3FUL) << DMAC_LSTDSTREG_LSTDST_WE_POS)
#define DMAC_LSTDSTREG_LSTDST_WE						DMAC_LSTDSTREG_LSTDST_WE_MASK

/*DMAC Configuration Register*/
#define DMAC_CFGREG_L_DMA_EN_POS                        (0UL)
#define DMAC_CFGREG_L_DMA_EN_MASK                       ((0X1UL) << DMAC_CFGREG_L_DMA_EN_POS)
#define DMAC_CFGREG_L_DMA                               DMAC_CFGREG_L_DMA_EN_MASK

/*DMAC Channel Enable Register*/
#define DMAC_CHENREG_L_CH_EN_POS						(0UL)
#define DMAC_CHENREG_L_CH_EN_MASK						((0X3FUL) << DMAC_CHENREG_L_CH_EN_POS)
#define DMAC_CHENREG_L_CH_EN							DMAC_CHENREG_L_CH_EN_MASK
#define DMAC_CHENREG_L_CH_EN_WE_POS						(8UL)
#define DMAC_CHENREG_L_CH_EN_WE_MASK					((0X3FUL) << DMAC_CHENREG_L_CH_EN_WE_POS)
#define DMAC_CHENREG_L_CH_EN_WE							DMAC_CHENREG_L_CH_EN_WE_MASK

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* BLE_SOC_XXX_MS_DMAC_REGS_H_ */
